### ISSUE TITLE
Forgot password link on login page redirection is wrong. [WebAdmin]

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#1]
Steps to replicate:

1. Navigate to https://www.stagingwin.com:6108/webadmin/auth/login
2. Click on 'Forgot Password?'

Expected Result:
User should be redirected to Forgot Password page where a user can request/update password.

Actual Result:
User is redirected to the customer portal.

Screen:
https://www.screencast.com/t/Oq4rb9Rh

**Comment by talhakpg** [comment]
Verified the fix. Thanks

**Comment by hassanahak** [comment]
to be discussed with @talhakpg
