### ISSUE TITLE
Align header elements to Right IF AR and to the Left IF EN

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#11]
![Tashafi-Healthcare 2021-07-20 09-15-44](https://user-images.githubusercontent.com/7084124/126306801-e9dd6674-f182-452d-8cff-a8f1f6f5a17c.png)

**Comment by talhakpg** [comment]
![image](https://user-images.githubusercontent.com/11936336/127463863-50f5d7ec-16e6-47e9-87d6-eda7a6b64c59.png)

**Comment by talhakpg** [comment]
![image](https://user-images.githubusercontent.com/11936336/127464010-bdf5c1f5-236b-44ae-8385-263ae0cc1b8e.png)

**Comment by talhakpg** [comment]
![image](https://user-images.githubusercontent.com/11936336/127464278-0da55c3a-befa-442f-b18e-6272965f730a.png)

**Comment by talhakpg** [comment]
Verified the fixes.
