### ISSUE TITLE
Button is not functioning or redirecting to the page which has the text

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#12]
![Tashafi-Healthcare 2021-07-20 09-18-18](https://user-images.githubusercontent.com/7084124/126306917-bf98e197-fd5f-4c2b-a8ed-316b51683bbb.png)

**Comment by Aseem2345** [comment]
Remove this button because our content is less so no need of this button

**Comment by adhamgsalem** [comment]
Button is removed.
