### ISSUE TITLE
When clicking on DR's photo, name then we should be redirected to his page (remove the view profile button)

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#14]
![Tashafi-Healthcare 🔊 2021-07-20 09-48-08](https://user-images.githubusercontent.com/7084124/126307265-3718c87d-accf-48cf-aebf-8fe97cc0cd4d.png)

**Comment by Aseem2345** [comment]
done

**Comment by adhamgsalem** [comment]
Fixed.
