### ISSUE TITLE
Translation needed for the days displayed in AR

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#15]
![Tashafi-Healthcare 2021-07-20 09-51-17](https://user-images.githubusercontent.com/7084124/126307876-24a701ab-9518-4bd3-a6d5-931dba8d3eca.png)

**Comment by Mahinder-Singh** [comment]
Done

**Comment by adhamgsalem** [comment]
@Mahinder-Singh the days are not properly displayed in ARABIC - we need to display the full text, not initials as we do in EN.

**Comment by adhamgsalem** [comment]
Fixed.
