### ISSUE TITLE
Gender need to be translated to AR

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#17]
![Tashafi-Healthcare 2021-07-20 09-52-16](https://user-images.githubusercontent.com/7084124/126308226-a64a4239-fa24-4d0d-bed9-50dcef628d8c.png)

**Comment by Mahinder-Singh** [comment]
For this we need to add Arabic data in db because all the content in dropdownlist are coming from db and for in arabic version we have decided with hassan what we have inserted in the db will show on the dropdownlist, either it is inserted in Arabic or English

**Comment by hassanahak** [comment]
Sure please Adham provide them with English and Arabic, to add it in DB

**Comment by adhamgsalem** [comment]
Male ذكر
Female أنثى

**Comment by adhamgsalem** [comment]
Fixed
