### ISSUE TITLE
Zip textbox has placeholder typo.[Needs approval]

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#2]
'ZSip' should be 'Zip'.

![image](https://user-images.githubusercontent.com/11936336/126036288-85df96a9-6cca-4026-81e8-f2b318849242.png)

**Comment by talhakpg** [comment]
This section has been removed. Can't verify.

**Comment by hassanahak** [comment]
to make finalize it with Talha.
