### ISSUE TITLE
Text needs to be changed in homepage 2 (make sure AR text is RTL and not messed up)

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#23]
![Tashafi-Healthcare 2021-07-20 10-04-33](https://user-images.githubusercontent.com/7084124/126311249-a0440add-779f-4d01-b208-a334800d0e1d.png)

AR
يمكنك مقابلة الطبيب بسهولة من خلال مكالمات لفيديو في الزمان و المكان مناسب لك
مكن لأطبئنامشاهدة لغة جسدك ويسمع صوتك من خلال مكالمة الفيديو
أويمكن أن يقدمون لك أستشارتك في المكانالمريح لك ,

فيديو تعريفي عن خدمات تشافي و كيفية الحصول عليها و يشمل الفديو التعريفي :
	•	كيفية التسجيل و الدخول مع الحفاظ على سريتك و خصوصيتك التامة
	•	كيفية حجز الموعد مع مستشارك العلاجي للحصول على الخدمة الأنسب لك

	•	كيفية الدفع بكل سهولة من خلال طرق الدفع المتنوعة

EN
You can easily meet the doctor through video calls at the time and place that suits you
Our doctors can see your body language and hear your voice through a video call
Or they can provide you with advice in a place that is convenient for you,

An introductory video about Xavi services and how to obtain them. The introductory video includes:
• How to register and log in while maintaining your confidentiality and complete privacy.
• How to book an appointment with your medical advisor to get the most suitable service for you

• How to pay with ease through various payment methods.

**Comment by Mahinder-Singh** [comment]
Done

**Comment by adhamgsalem** [comment]
Fixed.

**Comment by hassanahak** [comment]
**need to remove** 

AR
يمكنك مقابلة الطبيب بسهولة من خلال مكالمات لفيديو في الزمان و المكان مناسب لك
مكن لأطبئنامشاهدة لغة جسدك ويسمع صوتك من خلال مكالمة الفيديو
أويمكن أن يقدمون لك أستشارتك في المكانالمريح لك ,

EN
You can easily meet the doctor through video calls at the time and place that suits you
Our doctors can see your body language and hear your voice through a video call
Or they can provide you with advice in a place that is convenient for you,

**Need to replace :** 
Xavi to Tashafi

**Comment by hassanahak** [comment]
kindly Mahindra , include the Designers Gurpert ,  to improve the quality of home page looking . I need his help let us have a meeting with him.

**Comment by hassanahak** [comment]
فيديو تعريفي عن خدمات تشافي للرعاية الطبية و كيفية الحصول عليها و يشمل الفديو التعريفي:  
• كيفية التسجيل و الدخول مع الحفاظ على سريتك و خصوصيتك التامة
• كيفية حجز الموعد مع مستشارك العلاجي للحصول على الخدمة الأنسب لك
•	كيفية الدفع بكل سهولة من خلال طرق الدفع المتنوعة

**Comment by hassanahak** [comment]
فيديو تعريفي عن خدمات تشافي للرعاية الطبية و كيفية الحصول عليها و يشمل الفديو التعريفي:
• كيفية التسجيل و الدخول مع الحفاظ على سريتك و خصوصيتك التامة
• كيفية حجز الموعد مع مستشارك العلاجي للحصول على الخدمة الأنسب لك
• كيفية الدفع بكل سهولة من خلال طرق الدفع المتنوعة

please contact me Mahinder to discuss it with you .

**Comment by talhakpg** [comment]
> **need to remove**
> 
> AR
> يمكنك مقابلة الطبيب بسهولة من خلال مكالمات لفيديو في الزمان و المكان مناسب لك
> مكن لأطبئنامشاهدة لغة جسدك ويسمع صوتك من خلال مكالمة الفيديو
> أويمكن أن يقدمون لك أستشارتك في المكانالمريح لك ,
> 
> EN
> You can easily meet the doctor through video calls at the time and place that suits you
> Our doctors can see your body language and hear your voice through a video call
> Or they can provide you with advice in a place that is convenient for you,
> 
> **Need to replace :**
> Xavi to Tashafi

Xavi not yet been replaced.

**Comment by Aseem2345** [comment]
@hassanahak kindly replace the Xavi with Tashafi 
فيديو تعريفي عن خدمات تشافي و كيفية الحصول عليها و يشمل الفديو التعريفي

**Comment by talhakpg** [comment]
Verified the fix. Thanks!
