### ISSUE TITLE
When language = AR then display the text in browser tab in AR

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#24]
![Tashafi-Healthcare 2021-07-20 14-44-27](https://user-images.githubusercontent.com/7084124/126334799-77864da6-0e0f-4811-8487-b31a351e76cf.png)

AR
تشافي للرعاية الطبية

EN
Tashafi healthcare

**Comment by adhamgsalem** [comment]
Fixed.

**Comment by hassanahak** [comment]
thanks so much 👍
