### ISSUE TITLE
Valid Saudi phone number is shown invalid.

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#26]
Saudi phone numbers have 9 digits. I have used a valid Saudi phone number and it says invalid.

![image](https://user-images.githubusercontent.com/11936336/126436853-a7677b9b-8b92-42e2-a618-e31d835ae9a1.png)

**Comment by talhakpg** [comment]
@hassanahak @Mahinder-Singh We decided that we go with the 10 digit phone number where we will have '05xx-xxx-xxx) in the placeholder.

**Comment by talhakpg** [comment]
Here, in the placeholder show '05xx-xxx-xxx' rather than 'Phone Number' as mentioned above.

![image](https://user-images.githubusercontent.com/11936336/126595349-724827a0-6458-4eca-8dc4-194e8ce9d44a.png)

**Comment by talhakpg** [comment]
Place the same here too, this is 'Add user' under 'Manage Users'
![image](https://user-images.githubusercontent.com/11936336/126595879-c5f65206-166b-4670-84eb-ebc20a2b319a.png)

**Comment by talhakpg** [comment]
![image](https://user-images.githubusercontent.com/11936336/126714260-8a2bc9b1-92c0-4e47-8f71-054d95bd864f.png)

**Comment by Aseem2345** [comment]
![PhoneNumber](https://user-images.githubusercontent.com/82496795/127094589-d094e16a-28ff-4609-946f-babfed6f1c69.png)

**Comment by talhakpg** [comment]
Verified the fix.
