### ISSUE TITLE
Mark 'Gender' and 'Role' fields as mandatory 

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#27]
All the fields are marked as mandatory except these two while in function they too are mandatory.

![image](https://user-images.githubusercontent.com/11936336/126437566-79e79d66-4443-41eb-91d6-bb62be09da80.png)

**Comment by talhakpg** [comment]
Verified the fix. Thanks.

**Comment by hassanahak** [comment]
Thanks so much 🌹.
