### ISSUE TITLE
States should list Saudi states

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#30]
Currently shows US states.

![image](https://user-images.githubusercontent.com/11936336/126444609-0ae91c29-ac88-447a-97b4-9a867995c30b.png)

**Comment by talhakpg** [comment]
This is not yet fixed completely. We still have some US states being shown on the list. Please clear those.
[Note: Clear all the US states, not only the ones shown in the pic.]

![image](https://user-images.githubusercontent.com/11936336/126594531-670bae80-1112-4226-a269-614def464e2a.png)

**Comment by Aseem2345** [comment]
Done check again

**Comment by hassanahak** [comment]
Please lea

**Comment by hassanahak** [comment]
Hi Mahinder , I reopened it to be closed by the QA as we discuss before. Thanks so much for your understanding 🌹🌹. Please , need to Have every ticket closed by the one who created it.

**Comment by Mahinder-Singh** [comment]
no problem hassan .

**Comment by talhakpg** [comment]
@hassanahak can we have a complete list of states properly. The list has a mix of states and cities. Unayza and Buraidah are listed as states. 
@Mahinder-Singh Plea make sure after the list provided by @hassanahak that only the listed states appear.

**Comment by hassanahak** [comment]
Need discussion with Talha. please raise it in the next contact with me.

**Comment by hassanahak** [comment]
Abhā  أبها 
Abqaiq بقيق 
Abū 'Arīsh  أبو عريش 
Dammam الدمام  
Dawādmī  الدوادمي 
Ad-Dilam  الدلم
Ad-Dir'iyah الدرعية 
'Afïf عفيف RYD 
Aḥad al-Masāriḥah  أحد المسارحة
Aḥad Rāfidah  أحد رفيدة
Al-'Awāmiyah  العوامية 
Al-Badā'i'a  البدائع 
Al-Bāḥah الباحة  BAH 
Al-Bukayriyah  البكيرية 
Al-Ḥawiyah  الحويه 
Al-Hufūf  الهفوف
Al-Jubail  الجبيل 
Al-Jumūm الجموم
Al-Khafjī الخفجي 
Al-Kharj  الخرج 
Al-Khubar  الخبر 
Al-Khurmah الخرمة 
Medina المدينة
Al-Majma'ah  المجمعة
Al-Makhwāh  المخواة 
Al-Midhnab المذنب
Al-Muzāḥimiyah  المزاحمية 
Al-Qaīṣūmah القيصومة 
Al-Qaṭīf  القطيف 
Al-Qudaīḥ  القديح
Al-Qunfudhah القنفذة 
Al-Qurayyāt  القريات 
Al-Qūway'iyah القويعية 
Al-Qūz  القوز
Al-'Ulā العلا 
Al-'Ulāyah العلاية 
Al-'Uyūn  العيون
Al-Wajh الوجه 
'Ank عنك 
An-Nimāṣ  النماص 
Nariyah النعيرية 
'Ar'ar  عرعر
Ar-Rass الرس 
Riyadh الرياض 
As-Sulayyil  السليل 
Ath-Thuqbah الثقبة 
Aṭ-Ṭa'if  الطائف 
Aṭ-Ṭaraf الطرف 
Dhahran الظهران 
Az-Zulfī الزلفي 
Badr بدر
Baḥrah بحرة 
Baljurashī بلجرشي
Bīsh  بيش 
Bisha بيشة
Buraydah بريدة
Ḍamad  ضمد 
Ḍubā'  ضباء
Dūmat al-Jandal دومة الجندل
Ḥafar al-Bāṭin  حفر الباطن 
Ha'il حائل 
Ḥaql  حقل 
 Hotat Bani Tamim حوطة بني تميم 
Jeddah جدة 
Jīzān  جيزان 
Khamis Mushait خميس مشيط  
Laylā  ليلى  
Makkah مكة  
Muḥā'yil  محائل  
Najran نجران 
Rābigh  رابغ  
Rafḥā' رفحاء 
Raḥīmah | رحيمة 
Ranyah رنية 
Rimāḥ رماح 
Ṣabyā  صبيا  
Safwa  صفوى  
Saīhāt  سيهات 
Sakākā  سكاكا 
Samtah صامطة 
Shaqraa | شقراء 
Sharūrah شرورة 
Tabouk | تبوك 
Tārūt تاروت
Taymā' تيماء 
Ṭubarjal  طبرجل
Ṭuraīf  طريف
Turubah تربة 
'Umluj  أملج
'Unaizah عنيزة 
Wādī ad-Dawāsir  وادي الدواسر
 Yanbu]  ينبع 
Ẓahrān al-Janūb ظهران الجنوب

**Comment by talhakpg** [comment]
@hassanahak The list you have put above is for cities. This issue is about states.

**Comment by hassanahak** [comment]
Is asked him to delete it

**Comment by hassanahak** [comment]
And to make cities manual

**Comment by talhakpg** [comment]
Closing this ticket as it is no longer required.
