### ISSUE TITLE
User is blocked from booking? No data displayed?

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#38]
![‎‫تشافي للرعاية الطبية‬‎ 2021-07-21 16-57-18](https://user-images.githubusercontent.com/7084124/126520819-bf361f2a-0142-4eab-9e9f-de3db372b9c4.png)

**Comment by Mahinder-Singh** [comment]
Adham need to select date then you can select time slot then proceed further.

![image](https://user-images.githubusercontent.com/61724385/126595350-30a88719-473f-49a3-ba80-cb3578892d71.png)

**Comment by adhamgsalem** [comment]
@Mahinder-Singh I think it's clear from the screenshot that there is no dates displayed at my end on the AR version?

**Comment by Mahinder-Singh** [comment]
Please see at my end its working fine

![image](https://user-images.githubusercontent.com/61724385/126640138-7ca22631-1982-4ea5-b225-1a07bd940c36.png)

**Comment by adhamgsalem** [comment]
fixed
