### ISSUE TITLE
Add tooltip for MRN

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#41]
On Provider account under Add client. Please add a tooltip for MRN.
English: Medical Record Number
Arabic: رقم الملف 

![image](https://user-images.githubusercontent.com/11936336/126602079-c7cc7bbf-29ca-4f14-962c-ab2f330a975f.png)

**Comment by Mahinder-Singh** [comment]
We have add Place holder which can easily define the MRN: Medical Record Number

**Comment by talhakpg** [comment]
Verified the fix. Thanks.
