### ISSUE TITLE
Desired address is not shown completely on the address field.

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#5]
Steps:

1. Navigate to https://www.stagingwin.com:6108/
2. Login using valid 'Provider' credentials
3. Expand 'Manage Users' Tab
4. Click 'Add User'
5. Type an address and select the sggested address.[Test data: Qassim University]

Expected:
The address field should be popluated with complete address as shown on suggestion.

Actual Result:
Only a part of the address is shown.

Screen:

https://user-images.githubusercontent.com/11936336/126065509-f9bf9406-d66e-4215-a617-d14e921d044e.mp4

**Comment by Mahinder-Singh** [comment]
This actually search is fetching data from google api if google has full address then we will get the full address otherwise what data in google database we get in the  result.

**Comment by talhakpg** [comment]
We need a solution for this. Let's discuss this on call. @Mahinder-Singh @hassanahak

**Comment by hassanahak** [comment]
Sure

**Comment by hassanahak** [comment]
Need discussion with Talha. please raise it in the next contact with me.

**Comment by Mahinder-Singh** [comment]
1. Country Essential, Remove State from User
2. City should be manual not essential
3.  Street Address not essential or manual
4. Zip Code manual not essential
5. Remove NPI #
6. Tax ID remove it
7. Provide all the dropdown List on Website
8. Degree need to be manual no dropdownlist
9. Rendering Provider Remove it
10. Online Pay rate not essential
11. Face to Face Pay rate not essential
12. Remove Health Category , 
13. Speciality and Services are not essential
14. Team and Taxonomy remove.
15. Tags remove
16. Apt/Unit Remove
17. Language

**Comment by talhakpg** [comment]
@Mahinder-Singh Please make the address manual (non google api based) and make it non mandatory.

**Comment by Mahinder-Singh** [comment]
Speciality and Services are not essential is not done because if it make it non essential so in future after adding the doctor that doctor will not see in doctor list or patient side while consulations so it is mandatory

**Comment by hassanahak** [comment]
So I will provide you here about specialty and services here.

**Comment by hassanahak** [comment]
please close this one @Mahinder-Singh @talhakpg 

What do you think Talha

**Comment by talhakpg** [comment]
The core issue of the ticket is fixed. I see a lot of other communication. Anything else needs to be taken care of @hassanahak ?

**Comment by hassanahak** [comment]
Yes please, go ahead to close it.
