### ISSUE TITLE
Service list needs to be translated

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#57]
![‎‫تشافي للرعاية الطبية‬‎ 2021-07-22 15-09-42](https://user-images.githubusercontent.com/7084124/126653576-44c8fa88-3bca-4119-b613-80e472e2b1d8.png)

@hassanahak please provide translations for this section

**Comment by Mahinder-Singh** [comment]
Please provide Translation for services @hassanahak

**Comment by hassanahak** [comment]
Please delete the this section in Arabic and English

**Comment by adhamgsalem** [comment]
Removed. Fixed.
