### ISSUE TITLE
Country dropdown has only 'US' as an option

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#6]
Steps:

1. Navigate to https://www.stagingwin.com:6108/
2. Login using valid 'Provider' credentials
3. Expand 'Manage Users' Tab
4. Click 'Add User'
5. Click on 'Country' Dropdown

Expected:
There should be other countries, or at least Saudi Arabia as an option.

Actual Result:

Only US is shown as an option.

Screen:
![image](https://user-images.githubusercontent.com/11936336/126065599-6671e96d-60f3-46bf-bea9-7beb5960d0a2.png)

**Comment by talhakpg** [comment]
Verified the fix. Thanks
![image](https://user-images.githubusercontent.com/11936336/126596647-bd5691d7-75ae-4b26-b77c-262529c7cfd1.png)

**Comment by hassanahak** [comment]
to finalize it with @talhakpg
