### ISSUE TITLE
Add guide for Blood Pressure reading format

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#65]
Add a placeholder or tooltip which guides the user with the Blood Pressure reading format

![image](https://user-images.githubusercontent.com/11936336/126693561-7c1cb80a-0082-4484-82f6-d070f3689eaa.png)

**Comment by hassanahak** [comment]
Change temperature to Celsius instead of F,  to become: 
Temperature C : درجة حرارة الجسم

**Comment by talhakpg** [comment]
Verified the fix. Thanks

**Comment by talhakpg** [comment]
@hassanahak should we not add 'C' at the end of Arabic field 'درجة حرارة الجسم' also?

**Comment by hassanahak** [comment]
No need

**Comment by talhakpg** [comment]
Well in that case this is fixed. Closing the ticket.
