### ISSUE TITLE
Resend function not working for User Invitation. 

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#68]
Steps:
1. Navigate to https://www.stagingwin.com:6108/
2. Login using super admin credential
3. Go to User Invitation.
4. Make a new Invitation.
5. Click on 'Resend' button under 'ACTIONS'

Expected :

The user should get the invitation twice

Actual:

The user does receive the invitation only once.

![image](https://user-images.githubusercontent.com/11936336/126721695-a4e44fc2-e216-481f-9898-f8a1c3637825.png)

**Comment by Mahinder-Singh** [comment]
Actually we programtically  check on db if once invitation has been sent it will not send again.

**Comment by Mahinder-Singh** [comment]
Its working fine at our end please clear cache it will work fine for you as well.

![image](https://user-images.githubusercontent.com/61724385/126783267-3421888f-044d-408a-b16b-44cb7729cbdf.png)

**Comment by talhakpg** [comment]
Verified the fix. Thanks!
