### ISSUE TITLE
Place a convention for accepting number. Accept only valid number.

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#8]
Steps:

1. Navigate to https://www.stagingwin.com:6108/
2. Login using valid 'Provider' credentials
3. Expand 'Manage Users' Tab
4. Click 'Add User'

Expected : 
The user should be able to enter only valid phone numbers.
![image](https://user-images.githubusercontent.com/11936336/126066811-b9b8fd65-3523-450c-b896-06e84f7c5542.png)

Actual: 
User is able to save invalid phone number.
![image](https://user-images.githubusercontent.com/11936336/126066692-92a69892-7947-49db-9b49-6e788caa48e1.png)

**Comment by Mahinder-Singh** [comment]
Done

**Comment by talhakpg** [comment]
Verified the fix. Thanks.
