### ISSUE TITLE
IF language is set to AR then the language settings should show the other language as EN

### ISSUE THREAD

**Issue by adhamgsalem** [talhakpg/TeleTashafi#9]
![Tashafi-Healthcare 2021-07-20 09-12-24](https://user-images.githubusercontent.com/7084124/126306565-2c35905a-bd7c-48d9-b55c-9fb9aee23fcd.png)

**Comment by Mahinder-Singh** [comment]
can you please provide more clarity on this actually we didn't understand the actuall scenario. So we can make changes according to you thank you

**Comment by adhamgsalem** [comment]
@Mahinder-Singh 
Let's say the website is displayed as ENGLISH then we need to see the language bar showing ARABIC.
IF the website is displayed in ARABIC then we need to see the language bar showing in ENGLISH.

**Comment by hassanahak** [comment]
Need to discuss this in today meeting to provide clarity to you Mahinder.

**Comment by talhakpg** [comment]
Verified the fix. Thanks.
