### ISSUE TITLE
Home Page revamp

### ISSUE THREAD

**Issue by talhakpg** [talhakpg/TeleTashafi#94]

**Comment by talhakpg** [comment]
Change no. 1:
Increase in size and cover most of the whitespace.
Add a book now button. " لحجز موعد"

in English make the Button “Book Now” .

Let the Button linked to Care provider page.

![image](https://user-images.githubusercontent.com/11936336/126936299-99a10bf2-7cf3-4afa-90ee-2e837adedf16.png)

![image](https://user-images.githubusercontent.com/11936336/126947351-d2139a26-238f-4c5d-a106-bc4e306b356b.png)

**Comment by talhakpg** [comment]
https://www.afaq.io/ - to be referred  for contact us design.

**Comment by talhakpg** [comment]
Change No. 2 - Change the font type and size. This @Mahinder-Singh will confirm if it a big task or a small one and accordingly we will decide when it needs to be done.
@hassanahak to provide the font style and size to be used.

**Comment by talhakpg** [comment]
Change No. 3 - Change 'Doctor' to ' Care providers' and for Arabic "مقدمي الخدمة"

![image](https://user-images.githubusercontent.com/11936336/126947473-c7801def-5c8b-4f81-a788-10ce47ded749.png)

**Comment by hassanahak** [comment]
- change Doctor up to Care providers.
- Care provider مقدمي الخدمة

**Comment by hassanahak** [comment]
Remove (( Book our Doctor ))

**Comment by talhakpg** [comment]
Change No. 4 - 

![image](https://user-images.githubusercontent.com/11936336/126948295-d619a541-ef93-489c-97d6-0ac18e9dbfee.png)

**Comment by talhakpg** [comment]
Change No. 5 - 
![image](https://user-images.githubusercontent.com/11936336/126948617-07ac1081-8dc1-413d-b098-e95039855b52.png)

**Comment by talhakpg** [comment]
Change no. 6 - 
![image](https://user-images.githubusercontent.com/11936336/126949233-86a33037-2927-4685-ba71-6bbf4093e6a3.png)

**Comment by talhakpg** [comment]
Change no. 7 - Change the video to TeleTashafi video. @hassanahak to provide links.

![image](https://user-images.githubusercontent.com/11936336/126949676-b990be58-ece6-4dbc-8f72-f05fb4fd61d3.png)

This video is yet to be provided. For now, we can put https://youtu.be/okmynLqKhHw

This section will have a fixed video talking about TeleTashafi.
The one below will have latest video on TeleTashafi youtube channel.

**Comment by Mahinder-Singh** [comment]
@hassanahak please provide the  **Change no. 7 - Change the video to TeleTashafi video. @hassanahak to provide links.**

**Comment by hassanahak** [comment]
Related links

https://youtu.be/okmynLqKhHw

https://twitter.com/teletashafi/status/1419706548574687233?s=21

https://www.facebook.com/100071108858602/posts/107135581666737/?d=n

https://www.instagram.com/p/CRzHr7VBfsu/?utm_medium=copy_link

0504375380 whatsapp

Teletashafi@gmail.com Email.

**Comment by Mahinder-Singh** [comment]
@hassanahak please provide the https://youtu.be/okmynLqKhHw the embeded link because it is not working with Iframe
for eg: https://youtu.be/embed/okmynLqKhHw

**Comment by talhakpg** [comment]
Verified all the fix. 
Will open a separate ticket for font and size.
@hassanahak please provide the embedded link for youtube video. will open a ticket for it then.
